### PR TITLE
dokku deployment

### PR DESCRIPTION
**Pull request by jpscharf**
- Update README with dokku deployment directions
- Update lumen to 5.1.1
- Add the following dokku specific files
  - composer.lock
  - Procfile
  - .buildpacks
  - nginx.conf
  - requirements.txt
  - runtime.txt

### CODE REVIEW

**Comment by Kapeli** [comment]
For someone that's completely illiterate when it comes to Heroku and anything like it (i.e. never used it), can you explain what this does?

**Comment by jpscharf** [comment]
It allows you to deploy a web application with a `git push`.
dokku, for example, uses docker containers:
1. It will create a container with PHP and Python Installed.
2. Inject the code pushed, run commands (e.g. composer update, php artisan migrate).

_caveat_: Any data written to the file system will be **_lost**_ between pushes, if any of the directories need to be permanent, volumes need to be used.

**Comment by Kapeli** [comment]
Sounds good. How will this affect non-Dokku users? As far as I can tell, only the stuff in `post-install-cmd` will get executed, which I think is fine.

**Comment by jpscharf** [comment]
I believe you are correct, the only thing that would be effected would be the `post-install-cmd`. You could keep `dokku` in its own branch, but you would have to rebase it whenever `master` is updated.

**Comment by Kapeli** [comment]
I think it's fine like this. I'll move it to a separate branch if it causes any issues. Thank you!

**Pull request merged**
